export const shorts = [
  {
    title: "Land of 1,000,000 Years Ago",
    type: "short story",
    handle: "land-of-1-000-000-years-ago",
    originallyPublishedIn: "",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1959,
  },
  {
    title: "Thirty-One of the Classics",
    type: "novella",
    handle: "thirty-one-of-the-classics",
    originallyPublishedIn: "",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1959,
  },
  {
    title: "Jumper",
    type: "short story",
    handle: "jumper",
    originallyPublishedIn: "Dave's Rag (1959)",
    collectedIn: "Secret Windows (2000)",
    notes: ["Self-published"],
    year: 1959,
  },
  {
    title: "Rush Call",
    type: "short story",
    handle: "rush-call",
    originallyPublishedIn: "Dave's Rag (1960)",
    collectedIn: "Secret Windows (2000)",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "The Cursed Expedition",
    type: "short story",
    handle: "the-cursed-expedition",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "I've Got to Get Away!",
    type: "short story",
    handle: "i-ve-got-to-get-away-",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "Hotel at the End of the Road",
    type: "short story",
    handle: "hotel-at-the-end-of-the-road",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "Never Look Behind You",
    type: "short story",
    handle: "never-look-behind-you",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "The Other Side of the Fog",
    type: "short story",
    handle: "the-other-side-of-the-fog",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "The Stranger",
    type: "short story",
    handle: "the-stranger",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "The Thing at the Bottom of the Well",
    type: "short story",
    handle: "the-thing-at-the-bottom-of-the-well",
    originallyPublishedIn: "People, Places and Things (1960)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1960,
  },
  {
    title: "The Pit and the Pendulum",
    type: "short story",
    handle: "the-pit-and-the-pendulum",
    originallyPublishedIn: "The Pit and the Pendulum (1961)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1961,
  },
  {
    title: "The Undead",
    type: "short story",
    handle: "the-undead",
    originallyPublishedIn: "The Undead (1963)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1963,
  },
  {
    title: "Trigger Finger",
    type: "short story",
    handle: "trigger-finger",
    originallyPublishedIn: "Trigger Finger (1963)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1963,
  },
  {
    title: "The Star Invaders",
    type: "short story",
    handle: "the-star-invaders",
    originallyPublishedIn: "The Star Invaders (1964)",
    collectedIn: "Uncollected",
    notes: ["Self-published"],
    year: 1964,
  },
  {
    title: "Codename: Mousetrap",
    type: "short story",
    handle: "codename-mousetrap",
    originallyPublishedIn: "The Drum (October 27, 1965)",
    collectedIn: "Uncollected",
    notes: ["Lisbon Falls High School publication"],
    year: 1965,
  },
  {
    title: "I Was a Teenage Grave Robber",
    type: "short story",
    handle: "i-was-a-teenage-grave-robber",
    originallyPublishedIn: "Comics Review (1965)",
    collectedIn: "Uncollected",
    notes: [
      "First published in Comics Review, 1965. Later reprinted in Stories of Suspense (1965) retitled as “In a Half-World of Terror”. Partly reprinted in The Stephen King Illustrated Companion (edited by Bev Vincent, 2009).",
    ],
    year: 1965,
  },
  {
    title: "The 43rd Dream",
    type: "short story",
    handle: "the-43rd-dream",
    originallyPublishedIn: "The Drum (January 29, 1966)",
    collectedIn: "Uncollected",
    notes: ["Lisbon Falls High School publication"],
    year: 1966,
  },
  {
    title: "The Glass Floor",
    type: "short story",
    handle: "the-glass-floor",
    originallyPublishedIn: "Startling Mystery Stories (Fall 1967)",
    collectedIn: "Uncollected",
    notes: ["First professional story"],
    year: 1967,
  },
  {
    title: "Cain Rose Up",
    type: "short story",
    handle: "cain-rose-up",
    originallyPublishedIn: "Ubris (Spring 1968)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1968,
  },
  {
    title: "Here There Be Tygers",
    type: "short story",
    handle: "here-there-be-tygers",
    originallyPublishedIn: "Ubris (Spring 1968)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1968,
  },
  {
    title: "Harrison State Park '68",
    type: "poem",
    handle: "harrison-state-park-68",
    originallyPublishedIn: "Ubris (Fall 1968)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1968,
  },
  {
    title: "Strawberry Spring",
    type: "short story",
    handle: "strawberry-spring",
    originallyPublishedIn: "Ubris (Fall 1968)",
    collectedIn: "Night Shift (1978)",
    notes: ["Collected heavily revised"],
    year: 1968,
  },
  {
    title: "Night Surf",
    type: "short story",
    handle: "night-surf",
    originallyPublishedIn: "Ubris (Spring 1969)",
    collectedIn: "Night Shift (1978)",
    notes: ["Collected heavily revised"],
    year: 1969,
  },
  {
    title: "The Reaper's Image",
    type: "short story",
    handle: "the-reaper-s-image",
    originallyPublishedIn: "Startling Mystery Stories (Spring 1969)",
    collectedIn: "Skeleton Crew (1985)",
    notes: ["Collected heavily revised"],
    year: 1969,
  },
  {
    title: "The Dark Man",
    type: "poem",
    handle: "the-dark-man",
    originallyPublishedIn: "Ubris (Fall 1969)",
    collectedIn: "Uncollected",
    notes: ["Republished as a standalone book (2013)"],
    year: 1969,
  },
  {
    title: "Stud City",
    type: "short story",
    handle: "stud-city",
    originallyPublishedIn: "Ubris (Fall 1969)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into The Body (1982)"],
    year: 1969,
  },
  {
    title: "Slade",
    type: "short story",
    handle: "slade",
    originallyPublishedIn: "The Maine Campus (June 11 – August 6, 1970)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1970,
  },
  {
    title: "Graveyard Shift",
    type: "short story",
    handle: "graveyard-shift",
    originallyPublishedIn: "Cavalier (October 1970)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1970,
  },
  {
    title: "Donovan's Brain",
    type: "poem",
    handle: "donovan-s-brain",
    originallyPublishedIn: "Moth  (1970)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1970,
  },
  {
    title: "Silence",
    type: "poem",
    handle: "silence",
    originallyPublishedIn: "Moth  (1970)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1970,
  },
  {
    title: "The Blue Air Compressor",
    type: "short story",
    handle: "the-blue-air-compressor",
    originallyPublishedIn: "Onan (January 1971)",
    collectedIn: "Uncollected",
    notes: ["Republished revised in Heavy Metal (July 1981)"],
    year: 1971,
  },
  {
    title: "In the Key Chords of Dawn",
    type: "poem",
    handle: "in-the-key-chords-of-dawn",
    originallyPublishedIn: "Onan (January 1971)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1971,
  },
  {
    title: "I Am the Doorway",
    type: "short story",
    handle: "i-am-the-doorway",
    originallyPublishedIn: "Cavalier (March 1971)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1971,
  },
  {
    title: "Brooklyn August",
    type: "poem",
    handle: "brooklyn-august",
    originallyPublishedIn: "Io #10 (1971)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1971,
  },
  {
    title: "She Has Gone to Sleep While...",
    type: "poem",
    handle: "she-has-gone-to-sleep-while-",
    originallyPublishedIn: "Contraband #1 (1971)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1971,
  },
  {
    title: "Woman with Child",
    type: "poem",
    handle: "woman-with-child",
    originallyPublishedIn: "Contraband #1 (1971)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1971,
  },
  {
    title: "The Hardcase Speaks",
    type: "poem",
    handle: "the-hardcase-speaks",
    originallyPublishedIn: "Contraband #2 (1971)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1971,
  },
  {
    title: "Suffer the Little Children",
    type: "short story",
    handle: "suffer-the-little-children",
    originallyPublishedIn: "Cavalier (February 1972)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1972,
  },
  {
    title: "The Fifth Quarter",
    type: "short story",
    handle: "the-fifth-quarter",
    originallyPublishedIn: "Cavalier (April 1972)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["As John Swithen"],
    year: 1972,
  },
  {
    title: "Battleground",
    type: "short story",
    handle: "battleground",
    originallyPublishedIn: "Cavalier (September 1972)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1972,
  },
  {
    title: "The Mangler",
    type: "short story",
    handle: "the-mangler",
    originallyPublishedIn: "Cavalier (December 1972)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1972,
  },
  {
    title: "The Boogeyman",
    type: "short story",
    handle: "the-boogeyman",
    originallyPublishedIn: "Cavalier (March 1973)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1973,
  },
  {
    title: "Trucks",
    type: "short story",
    handle: "trucks",
    originallyPublishedIn: "Cavalier (June 1973)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1973,
  },
  {
    title: "Gray Matter",
    type: "short story",
    handle: "gray-matter",
    originallyPublishedIn: "Cavalier (October 1973)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1973,
  },
  {
    title: "It Grows on You",
    type: "short story",
    handle: "it-grows-on-you",
    originallyPublishedIn: "Marshroots (Fall 1973)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [
      "Republished revised in Whispers (August 1982), collected further revisedNominee, Locus Award, 1983[2]",
    ],
    year: 1973,
  },
  {
    title: "Sometimes They Come Back",
    type: "short story",
    handle: "sometimes-they-come-back",
    originallyPublishedIn: "Cavalier (March 1974)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1974,
  },
  {
    title: "The Lawnmower Man",
    type: "short story",
    handle: "the-lawnmower-man",
    originallyPublishedIn: "Cavalier (May 1975)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1975,
  },
  {
    title: "The Revenge of Lard Ass Hogan",
    type: "short story",
    handle: "the-revenge-of-lard-ass-hogan",
    originallyPublishedIn: "The Maine Review (July 1975)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into The Body (1982)"],
    year: 1975,
  },
  {
    title: "Weeds",
    type: "short story",
    handle: "weeds",
    originallyPublishedIn: "Cavalier (May 1976)",
    collectedIn: "Uncollected",
    notes: [
      "Appears in comic book form in Creepshow (1982) as The Lonesome Death of Jordy Verrill",
    ],
    year: 1976,
  },
  {
    title: "The Ledge",
    type: "short story",
    handle: "the-ledge",
    originallyPublishedIn: "Penthouse (July 1976)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1976,
  },
  {
    title: "I Know What You Need",
    type: "short story",
    handle: "i-know-what-you-need",
    originallyPublishedIn: "Cosmopolitan (September 1976)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1976,
  },
  {
    title: "Children of the Corn",
    type: "short story",
    handle: "children-of-the-corn",
    originallyPublishedIn: "Penthouse (March 1977)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1977,
  },
  {
    title: "One for the Road",
    type: "short story",
    handle: "one-for-the-road",
    originallyPublishedIn: "Maine (March/April 1977)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1977,
  },
  {
    title: "The Cat from Hell",
    type: "short story",
    handle: "the-cat-from-hell",
    originallyPublishedIn: "Cavalier (June 1977)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 1977,
  },
  {
    title: "The King Family and the Wicked Witch",
    type: "short story",
    handle: "the-king-family-and-the-wicked-witch",
    originallyPublishedIn: "Flint (August 25, 1977)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1977,
  },
  {
    title: "The Man Who Loved Flowers",
    type: "short story",
    handle: "the-man-who-loved-flowers",
    originallyPublishedIn: "Gallery (August 1977)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1977,
  },
  {
    title: "Jerusalem's Lot",
    type: "short story",
    handle: "jerusalem-s-lot",
    originallyPublishedIn: "Night Shift (February 1978)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1978,
  },
  {
    title: "The Last Rung on the Ladder",
    type: "short story",
    handle: "the-last-rung-on-the-ladder",
    originallyPublishedIn: "Night Shift (February 1978)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1978,
  },
  {
    title: "Quitters, Inc.",
    type: "short story",
    handle: "quitters-inc-",
    originallyPublishedIn: "Night Shift (February 1978)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1978,
  },
  {
    title: "The Woman in the Room",
    type: "short story",
    handle: "the-woman-in-the-room",
    originallyPublishedIn: "Night Shift (February 1978)",
    collectedIn: "Night Shift (1978)",
    notes: [],
    year: 1978,
  },
  {
    title: "The Night of the Tiger",
    type: "short story",
    handle: "the-night-of-the-tiger",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (February 1978)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1978,
  },
  {
    title: "Nona",
    type: "short story",
    handle: "nona",
    originallyPublishedIn: "Shadows (September 1978)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1978,
  },
  {
    title: "The Gunslinger",
    type: "novella",
    handle: "the-gunslinger",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (October 1978)",
    collectedIn: "The Dark Tower: The Gunslinger (1982)",
    notes: ["Collected revised", "Nominee, Locus Award, 1978[2]"],
    year: 1978,
  },
  {
    title: "Man With a Belly",
    type: "short story",
    handle: "man-with-a-belly",
    originallyPublishedIn: "Cavalier (December 1978)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1978,
  },
  {
    title: "The Crate",
    type: "short story",
    handle: "the-crate",
    originallyPublishedIn: "Gallery (July 1979)",
    collectedIn: "Uncollected",
    notes: [
      "Appears in comic book form in Creepshow (1982)Nominee, Locus Award, 1980[2]",
    ],
    year: 1979,
  },
  {
    title: "The Mist",
    type: "novella",
    handle: "the-mist",
    originallyPublishedIn: "Dark Forces (January 1, 1980)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [
      "Nominee, World Fantasy Award, 1981",
      "Nominee, Locus Award, 1981[2]",
    ],
    year: 1980,
  },
  {
    title: "Crouch End",
    type: "short story",
    handle: "crouch-end",
    originallyPublishedIn: "New Tales of the Cthulhu Mythos (January 1980)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Nominee, British Fantasy Award, 1981[2]"],
    year: 1980,
  },
  {
    title: "The Way Station",
    type: "novella",
    handle: "the-way-station",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (April 1980)",
    collectedIn: "The Dark Tower: The Gunslinger (1982)",
    notes: [
      "Collected revised",
      "Nominee, Nebula Award,1981",
      "Nominee, Locus Award, 1981[2]",
    ],
    year: 1980,
  },
  {
    title: "Big Wheels: A Tale of the Laundry Game (Milkman #2)",
    type: "short story",
    handle: "big-wheels-a-tale-of-the-laundry-game-milkman-2-",
    originallyPublishedIn: "New Terrors (July 1980)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1980,
  },
  {
    title: "The Monkey",
    type: "short story",
    handle: "the-monkey",
    originallyPublishedIn: "Gallery (November 1980)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [
      "Collected heavily revised",
      "Nominee, British Fantasy Award, 1982[2]",
    ],
    year: 1980,
  },
  {
    title: "The Wedding Gig",
    type: "short story",
    handle: "the-wedding-gig",
    originallyPublishedIn: "Ellery Queen's Mystery Magazine (December 1980)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1980,
  },
  {
    title: "The Oracle and the Mountains",
    type: "novella",
    handle: "the-oracle-and-the-mountains",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (February 1981)",
    collectedIn: "The Dark Tower: The Gunslinger (1982)",
    notes: ["Collected revised"],
    year: 1981,
  },
  {
    title: "The Jaunt",
    type: "short story",
    handle: "the-jaunt",
    originallyPublishedIn: "The Twilight Zone Magazine (June 1981)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1981,
  },
  {
    title: "The Slow Mutants",
    type: "novella",
    handle: "the-slow-mutants",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (July 1981)",
    collectedIn: "The Dark Tower: The Gunslinger (1982)",
    notes: ["Collected revised"],
    year: 1981,
  },
  {
    title: "The Man Who Would Not Shake Hands",
    type: "short story",
    handle: "the-man-who-would-not-shake-hands",
    originallyPublishedIn: "Shadows 4 (October 1981)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1981,
  },
  {
    title: "The Monster in the Closet",
    type: "short story",
    handle: "the-monster-in-the-closet",
    originallyPublishedIn: "Ladies' Home Journal (October 1981)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into Cujo (1981)"],
    year: 1981,
  },
  {
    title: "The Bird and the Album",
    type: "short story",
    handle: "the-bird-and-the-album",
    originallyPublishedIn: "A Fantasy Reader (October 30, 1981)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into It (1986)"],
    year: 1981,
  },
  {
    title: "The Gunslinger and the Dark Man",
    type: "novella",
    handle: "the-gunslinger-and-the-dark-man",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (November 1981)",
    collectedIn: "The Dark Tower: The Gunslinger (1982)",
    notes: ["Collected revised"],
    year: 1981,
  },
  {
    title: "The Reach",
    type: "short story",
    handle: "the-reach",
    originallyPublishedIn: "Yankee (November 1981)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [
      "Originally titled Do the Dead Sing?Nominee, World Fantasy Award, 1982[2]",
    ],
    year: 1981,
  },
  {
    title: "Survivor Type",
    type: "short story",
    handle: "survivor-type",
    originallyPublishedIn: "Terrors (July 1982)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1982,
  },
  {
    title: "Before the Play",
    type: "short story",
    handle: "before-the-play",
    originallyPublishedIn: "Whispers (August 1982)",
    collectedIn: "Uncollected",
    notes: ["Unused prologue to The Shining (1977)"],
    year: 1982,
  },
  {
    title: "Apt Pupil",
    type: "novella",
    handle: "apt-pupil",
    originallyPublishedIn: "Different Seasons (August 27, 1982)",
    collectedIn: "Different Seasons (1982)",
    notes: ["Nominee, British Fantasy Award, 1983[2]"],
    year: 1982,
  },
  {
    title: "The Body",
    type: "novella",
    handle: "the-body",
    originallyPublishedIn: "Different Seasons (August 27, 1982)",
    collectedIn: "Different Seasons (1982)",
    notes: [],
    year: 1982,
  },
  {
    title: "The Breathing Method",
    type: "novella",
    handle: "the-breathing-method",
    originallyPublishedIn: "Different Seasons (August 27, 1982)",
    collectedIn: "Different Seasons (1982)",
    notes: [
      "Winner, British Fantasy Award, 1983",
      "Nominee, World Fantasy Award, 1983",
      "Nominee, Locus Award, 1983[2]",
    ],
    year: 1982,
  },
  {
    title: "Rita Hayworth and Shawshank Redemption",
    type: "novella",
    handle: "rita-hayworth-and-shawshank-redemption",
    originallyPublishedIn: "Different Seasons (August 27, 1982)",
    collectedIn: "Different Seasons (1982)",
    notes: [],
    year: 1982,
  },
  {
    title: "The Raft",
    type: "short story",
    handle: "the-raft",
    originallyPublishedIn: "Gallery (November 1982)",
    collectedIn: "Skeleton Crew (1985)",
    notes: ["Nominee, Locus Award, 1983[2]"],
    year: 1982,
  },
  {
    title: "Skybar",
    type: "short story",
    handle: "skybar",
    originallyPublishedIn: "The Do-It-Yourself Bestseller (1982)",
    collectedIn: "Uncollected",
    notes: ["Partial short story"],
    year: 1982,
  },
  {
    title: "Word Processor of the Gods",
    type: "short story",
    handle: "word-processor-of-the-gods",
    originallyPublishedIn: "Playboy (January 1983)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [
      "Originally titled The Word Processor",
      " collected heavily revised",
    ],
    year: 1983,
  },
  {
    title: "Uncle Otto's Truck",
    type: "short story",
    handle: "uncle-otto-s-truck",
    originallyPublishedIn: "Yankee (October 1983)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1983,
  },
  {
    title: "Cycle of the Werewolf",
    type: "novella",
    handle: "cycle-of-the-werewolf",
    originallyPublishedIn: "Land of Enchantment (November 1983)",
    collectedIn: "Uncollected (standalone book)",
    notes: [],
    year: 1983,
  },
  {
    title: "The Return of Timmy Baterman",
    type: "short story",
    handle: "the-return-of-timmy-baterman",
    originallyPublishedIn: "Satyricon II (1983)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into Pet Sematary (1983)"],
    year: 1983,
  },
  {
    title: "Gramma",
    type: "short story",
    handle: "gramma",
    originallyPublishedIn: "Weirdbook (Spring 1984)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1984,
  },
  {
    title: "Mrs. Todd's Shortcut",
    type: "short story",
    handle: "mrs-todd-s-shortcut",
    originallyPublishedIn: "Redbook (May 1984)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1984,
  },
  {
    title: "The Ballad of the Flexible Bullet",
    type: "novella",
    handle: "the-ballad-of-the-flexible-bullet",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (June 1984)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [
      "Nominee, World Fantasy Award, 1985",
      "Nominee, Locus Award, 1985[2]",
    ],
    year: 1984,
  },
  {
    title: "The Revelations of 'Becka Paulson",
    type: "short story",
    handle: "the-revelations-of-becka-paulson",
    originallyPublishedIn: "Rolling Stone (July 19 – August 2, 1984)",
    collectedIn: "Uncollected",
    notes: [
      "Collected in the limited edition of Skeleton Crew (1985)",
      "incorporated into The Tommyknockers (1987)",
    ],
    year: 1984,
  },
  {
    title: "Beachworld",
    type: "short story",
    handle: "beachworld",
    originallyPublishedIn: "Weird Tales (Fall 1984)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1984,
  },
  {
    title: "Dolan's Cadillac",
    type: "novella",
    handle: "dolan-s-cadillac",
    originallyPublishedIn: "Castle Rock (February – June 1985)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1985,
  },
  {
    title: "For Owen",
    type: "poem",
    handle: "for-owen",
    originallyPublishedIn: "Skeleton Crew (June 1985)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1985,
  },
  {
    title: "Morning Deliveries (Milkman #1)",
    type: "short story",
    handle: "morning-deliveries-milkman-1-",
    originallyPublishedIn: "Skeleton Crew (June 1985)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1985,
  },
  {
    title: "Paranoid: A Chant",
    type: "poem",
    handle: "paranoid-a-chant",
    originallyPublishedIn: "Skeleton Crew (June 1985)",
    collectedIn: "Skeleton Crew (1985)",
    notes: [],
    year: 1985,
  },
  {
    title: "For the Birds",
    type: "short story",
    handle: "for-the-birds",
    originallyPublishedIn: "Bred Any Good Rooks Lately? (January 1986)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1986,
  },
  {
    title: "The End of the Whole Mess",
    type: "short story",
    handle: "the-end-of-the-whole-mess",
    originallyPublishedIn: "Omni (October 1986)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Nominee, World Fantasy Award, 1987[2]"],
    year: 1986,
  },
  {
    title: "Popsy",
    type: "short story",
    handle: "popsy",
    originallyPublishedIn: "Masques II (June 1987)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1987,
  },
  {
    title: "The Doctor's Case",
    type: "short story",
    handle: "the-doctor-s-case",
    originallyPublishedIn:
      "The New Adventures of Sherlock Holmes (November 1987)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1987,
  },
  {
    title: "The Night Flier",
    type: "short story",
    handle: "the-night-flier",
    originallyPublishedIn: "Prime Evil (June 1988)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Nominee, Bram Stoker Award, 1989[2]"],
    year: 1988,
  },
  {
    title: "Dedication",
    type: "short story",
    handle: "dedication",
    originallyPublishedIn: "Night Visions 5 (August 1988)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1988,
  },
  {
    title: "The Reploids",
    type: "short story",
    handle: "the-reploids",
    originallyPublishedIn: "Night Visions 5 (August 1988)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1988,
  },
  {
    title: "Sneakers",
    type: "short story",
    handle: "sneakers",
    originallyPublishedIn: "Night Visions 5 (August 1988)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1988,
  },
  {
    title: "Rainy Season",
    type: "short story",
    handle: "rainy-season",
    originallyPublishedIn: "Midnight Graffiti (Spring 1989)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1989,
  },
  {
    title: "Home Delivery",
    type: "short story",
    handle: "home-delivery",
    originallyPublishedIn: "Book of the Dead (June 1989)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1989,
  },
  {
    title: "My Pretty Pony",
    type: "short story",
    handle: "my-pretty-pony",
    originallyPublishedIn: "My Pretty Pony (September 1989)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Collected revised"],
    year: 1989,
  },
  {
    title: "An Evening at God's",
    type: "play",
    handle: "an-evening-at-god-s",
    originallyPublishedIn:
      "Institute for Advanced Theater Training (April 23, 1990)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1990,
  },
  {
    title: "The Langoliers",
    type: "novella",
    handle: "the-langoliers",
    originallyPublishedIn: "Four Past Midnight (September 1990)",
    collectedIn: "Four Past Midnight (1990)",
    notes: ["Nominee, Bram Stoker Award, 1991[2]"],
    year: 1990,
  },
  {
    title: "The Library Policeman",
    type: "novella",
    handle: "the-library-policeman",
    originallyPublishedIn: "Four Past Midnight (September 1990)",
    collectedIn: "Four Past Midnight (1990)",
    notes: [],
    year: 1990,
  },
  {
    title: "Secret Window, Secret Garden",
    type: "novella",
    handle: "secret-window-secret-garden",
    originallyPublishedIn: "Four Past Midnight (September 1990)",
    collectedIn: "Four Past Midnight (1990)",
    notes: [],
    year: 1990,
  },
  {
    title: "The Sun Dog",
    type: "novella",
    handle: "the-sun-dog",
    originallyPublishedIn: "Four Past Midnight (September 1990)",
    collectedIn: "Four Past Midnight (1990)",
    notes: [],
    year: 1990,
  },
  {
    title: "The Bear",
    type: "short story",
    handle: "the-bear",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (December 1990)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into The Dark Tower III: The Waste Lands (1991)"],
    year: 1990,
  },
  {
    title: "The Moving Finger",
    type: "short story",
    handle: "the-moving-finger",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (December 1990)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1990,
  },
  {
    title: "You Know They Got a Hell of a Band",
    type: "short story",
    handle: "you-know-they-got-a-hell-of-a-band",
    originallyPublishedIn: "Shock Rock (January 1992)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Collected heavily revised"],
    year: 1992,
  },
  {
    title: "Chattery Teeth",
    type: "short story",
    handle: "chattery-teeth",
    originallyPublishedIn: "Cemetery Dance (Fall 1992)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1992,
  },
  {
    title: "The Beggar and the Diamond",
    type: "short story",
    handle: "the-beggar-and-the-diamond",
    originallyPublishedIn: "Nightmares & Dreamscapes (September 1993)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1993,
  },
  {
    title: "The House on Maple Street",
    type: "short story",
    handle: "the-house-on-maple-street",
    originallyPublishedIn: "Nightmares & Dreamscapes (September 1993)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1993,
  },
  {
    title: "Sorry, Right Number",
    type: "teleplay",
    handle: "sorry-right-number",
    originallyPublishedIn: "Nightmares & Dreamscapes (September 1993)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Written in 1987"],
    year: 1993,
  },
  {
    title: "The Ten O'Clock People",
    type: "short story",
    handle: "the-ten-o-clock-people",
    originallyPublishedIn: "Nightmares & Dreamscapes (September 1993)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: ["Nominee, Locus Award, 1994[2]"],
    year: 1993,
  },
  {
    title: "Umney's Last Case",
    type: "short story",
    handle: "umney-s-last-case",
    originallyPublishedIn: "Nightmares & Dreamscapes (September 1993)",
    collectedIn: "Nightmares & Dreamscapes (1993)",
    notes: [],
    year: 1993,
  },
  {
    title: "Jhonathan and the Witches",
    type: "short story",
    handle: "jhonathan-and-the-witches",
    originallyPublishedIn: "First Words (October 1993)",
    collectedIn: "Uncollected",
    notes: ["Written in 1956"],
    year: 1993,
  },
  {
    title: "The Killer",
    type: "short story",
    handle: "the-killer",
    originallyPublishedIn: "Famous Monsters of Filmland #202 (Spring 1994)",
    collectedIn: "Uncollected",
    notes: ["Written in the mid-1960s"],
    year: 1994,
  },
  {
    title: "Blind Willie",
    type: "short story",
    handle: "blind-willie",
    originallyPublishedIn: "Antaeus #75/76 (October 1994)",
    collectedIn: "Hearts in Atlantis (1999)",
    notes: ["Collected heavily revised"],
    year: 1994,
  },
  {
    title: "The Man in the Black Suit",
    type: "short story",
    handle: "the-man-in-the-black-suit",
    originallyPublishedIn: "The New Yorker (October 31, 1994)",
    collectedIn: "Everything's Eventual (2002)",
    notes: ["Winner, World Fantasy Award, 1995[2]"],
    year: 1994,
  },
  {
    title: "Dino",
    type: "poem",
    handle: "dino",
    originallyPublishedIn: "Salt Hill Journal (Fall 1994)",
    collectedIn: "Uncollected",
    notes: [],
    year: 1994,
  },
  {
    title: "Luckey Quarter",
    type: "short story",
    handle: "luckey-quarter",
    originallyPublishedIn: "USA Weekend (June 30 – July 2, 1995)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 1995,
  },
  {
    title: "Lunch at the Gotham Café",
    type: "short story",
    handle: "lunch-at-the-gotham-café",
    originallyPublishedIn: "Dark Love (November 1995)",
    collectedIn: "Everything's Eventual (2002)",
    notes: ["Winner, Bram Stoker Award, 1996", "Nominee, Locus Award, 1996[2]"],
    year: 1995,
  },
  {
    title: "Autopsy Room Four",
    type: "short story",
    handle: "autopsy-room-four",
    originallyPublishedIn: "Six Stories (April 1997)",
    collectedIn: "Everything's Eventual (2002)",
    notes: ["Nominee, Bram Stoker Award, 1999[2]"],
    year: 1997,
  },
  {
    title: "L. T.'s Theory of Pets",
    type: "short story",
    handle: "l-t-s-theory-of-pets",
    originallyPublishedIn: "Six Stories (April 1997)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 1997,
  },
  {
    title: "General",
    type: "screenplay",
    handle: "general",
    originallyPublishedIn: "Screamplays  (September 1997)",
    collectedIn: "Uncollected",
    notes: ["Written around 1985 for the film Cat's Eye (1985)"],
    year: 1997,
  },
  {
    title: "Everything's Eventual",
    type: "novella",
    handle: "everything-s-eventual",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (October–November 1997)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [
      "Nominee, Bram Stoker Award, 1998",
      "Nominee, Locus Award, 1998[2]",
    ],
    year: 1997,
  },
  {
    title: "That Feeling, You Can Only Say What It Is in French",
    type: "short story",
    handle: "that-feeling-you-can-only-say-what-it-is-in-french",
    originallyPublishedIn: "The New Yorker (June 22, 1998)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 1998,
  },
  {
    title: "The Little Sisters of Eluria",
    type: "novella",
    handle: "the-little-sisters-of-eluria",
    originallyPublishedIn: "Legends (October 1998)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 1998,
  },
  {
    title: "The New Lieutenant's Rap",
    type: "short story",
    handle: "the-new-lieutenant-s-rap",
    originallyPublishedIn: "The New Lieutenant's Rap (April 1999)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into Why We're in Vietnam (1999)"],
    year: 1999,
  },
  {
    title: "The Road Virus Heads North",
    type: "short story",
    handle: "the-road-virus-heads-north",
    originallyPublishedIn: "999 (September 7, 1999)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 1999,
  },
  {
    title: "Hearts in Atlantis",
    type: "novella",
    handle: "hearts-in-atlantis",
    originallyPublishedIn: "Hearts in Atlantis (September 14, 1999)",
    collectedIn: "Hearts in Atlantis (1999)",
    notes: [],
    year: 1999,
  },
  {
    title: "Heavenly Shades of Night Are Falling",
    type: "short story",
    handle: "heavenly-shades-of-night-are-falling",
    originallyPublishedIn: "Hearts in Atlantis (September 14, 1999)",
    collectedIn: "Hearts in Atlantis (1999)",
    notes: [],
    year: 1999,
  },
  {
    title: "Low Men in Yellow Coats",
    type: "novella",
    handle: "low-men-in-yellow-coats",
    originallyPublishedIn: "Hearts in Atlantis (September 14, 1999)",
    collectedIn: "Hearts in Atlantis (1999)",
    notes: ["Nominee, Bram Stoker Award, 2000[2]"],
    year: 1999,
  },
  {
    title: "Why We're in Vietnam",
    type: "novella",
    handle: "why-we-re-in-vietnam",
    originallyPublishedIn: "Hearts in Atlantis (September 14, 1999)",
    collectedIn: "Hearts in Atlantis (1999)",
    notes: [],
    year: 1999,
  },
  {
    title: "1408",
    type: "short story",
    handle: "1408",
    originallyPublishedIn: "Blood and Smoke (November 1999)",
    collectedIn: "Everything's Eventual (2002)",
    notes: ["Originally published in an audiobook collection"],
    year: 1999,
  },
  {
    title: "In the Deathroom",
    type: "short story",
    handle: "in-the-deathroom",
    originallyPublishedIn: "Blood and Smoke (November 1999)",
    collectedIn: "Everything's Eventual (2002)",
    notes: ["Originally published in an audiobook collection"],
    year: 1999,
  },
  {
    title: "Riding the Bullet",
    type: "novella",
    handle: "riding-the-bullet",
    originallyPublishedIn: "Riding the Bullet (March 14, 2000)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [
      "Originally published as an ebookNominee, Bram Stoker Award, 2001[2]",
    ],
    year: 2000,
  },
  {
    title: "The Old Dude's Ticker",
    type: "short story",
    handle: "the-old-dude-s-ticker",
    originallyPublishedIn: "NECON XX (July 2000)",
    collectedIn: "Uncollected",
    notes: ["Written in the early 1970s"],
    year: 2000,
  },
  {
    title: "All That You Love Will Be Carried Away",
    type: "short story",
    handle: "all-that-you-love-will-be-carried-away",
    originallyPublishedIn: "The New Yorker (January 29, 2001)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 2001,
  },
  {
    title: "Calla Bryn Sturgis",
    type: "short story",
    handle: "calla-bryn-sturgis",
    originallyPublishedIn: "stephenking.com (2001)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into The Dark Tower V: Wolves of the Calla (2003)"],
    year: 2001,
  },
  {
    title: "The Death of Jack Hamilton",
    type: "short story",
    handle: "the-death-of-jack-hamilton",
    originallyPublishedIn: "The New Yorker (December 24–31, 2001)",
    collectedIn: "Everything's Eventual (2002)",
    notes: [],
    year: 2001,
  },
  {
    title: "The Tale of Gray Dick",
    type: "short story",
    handle: "the-tale-of-gray-dick",
    originallyPublishedIn:
      "McSweeney's Mammoth Treasury of Thrilling Tales (March 25, 2003)",
    collectedIn: "Uncollected",
    notes: ["Incorporated into The Dark Tower V: Wolves of the Calla (2003)"],
    year: 2003,
  },
  {
    title: "Harvey's Dream",
    type: "short story",
    handle: "harvey-s-dream",
    originallyPublishedIn: "The New Yorker (June 30, 2003)",
    collectedIn: "Just After Sunset (2008)",
    notes: ["Nominee, Bram Stoker Award, 2004[2]"],
    year: 2003,
  },
  {
    title: "Stationary Bike",
    type: "short story",
    handle: "stationary-bike",
    originallyPublishedIn: "Borderlands 5 (November 2003)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2003,
  },
  {
    title: "Rest Stop",
    type: "short story",
    handle: "rest-stop",
    originallyPublishedIn: "Esquire (December 2003)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2003,
  },
  {
    title: "Lisey and the Madman",
    type: "short story",
    handle: "lisey-and-the-madman",
    originallyPublishedIn:
      "McSweeney’s Enchanted Chamber of Astonishing Stories (2004)",
    collectedIn: "Uncollected",
    notes: [
      "Incorporated into Lisey's Story (2006)Nominee, Bram Stoker Award, 2005[2]",
    ],
    year: 2004,
  },
  {
    title: "The Furnace",
    type: "short story",
    handle: "the-furnace",
    originallyPublishedIn: "Weekly Reader (September 2005)",
    collectedIn: "Uncollected",
    notes: ["Partial short story"],
    year: 2005,
  },
  {
    title: "The Things They Left Behind",
    type: "short story",
    handle: "the-things-they-left-behind",
    originallyPublishedIn: "Transgressions  (May 2005)",
    collectedIn: "Just After Sunset (2008)",
    notes: ["Nominee, Bram Stoker Award, 2006[2]"],
    year: 2005,
  },
  {
    title: "Memory",
    type: "short story",
    handle: "memory",
    originallyPublishedIn: "Tin House #28 (July 2006)",
    collectedIn: "Blaze (2007)",
    notes: ["Incorporated into Duma Key (2008)"],
    year: 2006,
  },
  {
    title: "Willa",
    type: "short story",
    handle: "willa",
    originallyPublishedIn: "Playboy (December 2006)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2006,
  },
  {
    title: "Graduation Afternoon",
    type: "short story",
    handle: "graduation-afternoon",
    originallyPublishedIn: "Postscripts (March 2007)",
    collectedIn: "Just After Sunset (2008)",
    notes: ["Nominee, Locus Award, 2008[2]"],
    year: 2007,
  },
  {
    title: "The Gingerbread Girl",
    type: "novella",
    handle: "the-gingerbread-girl",
    originallyPublishedIn: "Esquire (July 2007)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2007,
  },
  {
    title: "Ayana",
    type: "short story",
    handle: "ayana",
    originallyPublishedIn: "The Paris Review (Fall 2007)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2007,
  },
  {
    title: "Mute",
    type: "short story",
    handle: "mute",
    originallyPublishedIn: "Playboy (December 2007)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2007,
  },
  {
    title: "A Very Tight Place",
    type: "novella",
    handle: "a-very-tight-place",
    originallyPublishedIn: "McSweeney's #27 (Spring 2008)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2008,
  },
  {
    title: "The New York Times at Special Bargain Rates",
    type: "short story",
    handle: "the-new-york-times-at-special-bargain-rates",
    originallyPublishedIn:
      "The Magazine of Fantasy & Science Fiction (October/November 2008)",
    collectedIn: "Just After Sunset (2008)",
    notes: [],
    year: 2008,
  },
  {
    title: "N.",
    type: "novella",
    handle: "n-",
    originallyPublishedIn: "Just After Sunset (November 2008)",
    collectedIn: "Just After Sunset (2008)",
    notes: ["Nominee, British Fantasy Award, 2009[2]"],
    year: 2008,
  },
  {
    title: "Throttle",
    type: "novella",
    handle: "throttle",
    originallyPublishedIn: "He Is Legend (February 1, 2009)",
    collectedIn: "Uncollected",
    notes: [
      "In collaboration with Joe Hill, part of Hill's collection Full Throttle",
    ],
    year: 2009,
  },
  {
    title: "Ur",
    type: "novella",
    handle: "ur",
    originallyPublishedIn: "Ur (February 12, 2009)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Originally published as an ebook", " collected heavily revised"],
    year: 2009,
  },
  {
    title: "Morality",
    type: "novella",
    handle: "morality",
    originallyPublishedIn: "Esquire (July 2009)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [
      "Previously included with the trade edition of Blockade Billy (2010)",
      "Winner, Shirley Jackson Award, 2009[2]",
    ],
    year: 2009,
  },
  {
    title: "Mostly Old Men",
    type: "poem",
    handle: "mostly-old-men",
    originallyPublishedIn: "Tin House #40 (August 2009)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2009,
  },
  {
    title: "The Bone Church",
    type: "poem",
    handle: "the-bone-church",
    originallyPublishedIn: "Playboy (November 2009)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2009,
  },
  {
    title: "Premium Harmony",
    type: "short story",
    handle: "premium-harmony",
    originallyPublishedIn: "The New Yorker (November 9, 2009)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2009,
  },
  {
    title: "Tommy",
    type: "poem",
    handle: "tommy",
    originallyPublishedIn: "Playboy (March 2010)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2010,
  },
  {
    title: "Blockade Billy",
    type: "novella",
    handle: "blockade-billy",
    originallyPublishedIn: "Blockade Billy (April 2010)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2010,
  },
  {
    title: "1922",
    type: "novella",
    handle: "1922",
    originallyPublishedIn: "Full Dark, No Stars (November 2010)",
    collectedIn: "Full Dark, No Stars (2010)",
    notes: ["Nominee, British Fantasy Award, 2011[2]"],
    year: 2010,
  },
  {
    title: "Big Driver",
    type: "novella",
    handle: "big-driver",
    originallyPublishedIn: "Full Dark, No Stars (November 2010)",
    collectedIn: "Full Dark, No Stars (2010)",
    notes: [],
    year: 2010,
  },
  {
    title: "Fair Extension",
    type: "novella",
    handle: "fair-extension",
    originallyPublishedIn: "Full Dark, No Stars (November 2010)",
    collectedIn: "Full Dark, No Stars (2010)",
    notes: [],
    year: 2010,
  },
  {
    title: "A Good Marriage",
    type: "novella",
    handle: "a-good-marriage",
    originallyPublishedIn: "Full Dark, No Stars (November 2010)",
    collectedIn: "Full Dark, No Stars (2010)",
    notes: [],
    year: 2010,
  },
  {
    title: "Herman Wouk Is Still Alive",
    type: "short story",
    handle: "herman-wouk-is-still-alive",
    originallyPublishedIn: "The Atlantic (May 2011)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Winner, Bram Stoker Award, 2012[2]"],
    year: 2011,
  },
  {
    title: "Under the Weather",
    type: "short story",
    handle: "under-the-weather",
    originallyPublishedIn:
      "Paperback edition of Full Dark, No Stars (May 2011)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2011,
  },
  {
    title: "Mile 81",
    type: "novella",
    handle: "mile-81",
    originallyPublishedIn: "Mile 81 (September 1, 2011)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Originally published as an ebook"],
    year: 2011,
  },
  {
    title: "The Little Green God of Agony",
    type: "short story",
    handle: "the-little-green-god-of-agony",
    originallyPublishedIn: "A Book of Horrors (September 29, 2011)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Adapted into a webcomic", "[3]Nominee, Locus Award, 2012[2]"],
    year: 2011,
  },
  {
    title: "The Dune",
    type: "short story",
    handle: "the-dune",
    originallyPublishedIn: "Granta #117 (Fall 2011)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2011,
  },
  {
    title: "In the Tall Grass",
    type: "novella",
    handle: "in-the-tall-grass",
    originallyPublishedIn: "Esquire (June/July–August 2012)",
    collectedIn: "Uncollected",
    notes: [
      "In collaboration with Joe Hill, part of Hill's collection Full Throttle",
    ],
    year: 2012,
  },
  {
    title: "A Face in the Crowd",
    type: "novella",
    handle: "a-face-in-the-crowd",
    originallyPublishedIn: "A Face in the Crowd (August 21, 2012)",
    collectedIn: "Uncollected",
    notes: [
      "Originally published as an ebook",
      " in collaboration with Stewart O'Nan",
    ],
    year: 2012,
  },
  {
    title: "Batman and Robin Have an Altercation",
    type: "short story",
    handle: "batman-and-robin-have-an-altercation",
    originallyPublishedIn: "Harper's Magazine (September 2012)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2012,
  },
  {
    title: "Afterlife",
    type: "short story",
    handle: "afterlife",
    originallyPublishedIn: "Tin House #56 (June 2013)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2013,
  },
  {
    title: "The Rock and Roll Dead Zone",
    type: "short story",
    handle: "the-rock-and-roll-dead-zone",
    originallyPublishedIn: "Hard Listening (June 18, 2013)",
    collectedIn: "Uncollected",
    notes: ["Originally published as an ebook"],
    year: 2013,
  },
  {
    title: "Summer Thunder",
    type: "short story",
    handle: "summer-thunder",
    originallyPublishedIn: "Turn Down the Lights (December 2013)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2013,
  },
  {
    title: "Bad Little Kid",
    type: "short story",
    handle: "bad-little-kid",
    originallyPublishedIn: "Bad Little Kid (March 14, 2014)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [
      "Originally published as an ebook in French and German languages only",
    ],
    year: 2014,
  },
  {
    title: "That Bus Is Another World",
    type: "short story",
    handle: "that-bus-is-another-world",
    originallyPublishedIn: "Esquire (August 2014)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2014,
  },
  {
    title: "A Death",
    type: "short story",
    handle: "a-death",
    originallyPublishedIn: "The New Yorker (March 9, 2015)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2015,
  },
  {
    title: "Drunken Fireworks",
    type: "short story",
    handle: "drunken-fireworks",
    originallyPublishedIn: "Drunken Fireworks (June 30, 2015)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Originally published as an audiobook"],
    year: 2015,
  },
  {
    title: "Mister Yummy",
    type: "short story",
    handle: "mister-yummy",
    originallyPublishedIn: "The Bazaar of Bad Dreams (November 2015)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: [],
    year: 2015,
  },
  {
    title: "Obits",
    type: "short story",
    handle: "obits",
    originallyPublishedIn: "The Bazaar of Bad Dreams (November 2015)",
    collectedIn: "The Bazaar of Bad Dreams (2015)",
    notes: ["Nominee, Hugo Award, 2016[2]"],
    year: 2015,
  },
  {
    title: "Cookie Jar",
    type: "short story",
    handle: "cookie-jar",
    originallyPublishedIn: "Virginia Quarterly Review (Spring 2016)",
    collectedIn: "Uncollected",
    notes: [
      "Appears in the paperback edition of The Bazaar of Bad Dreams (2016)",
    ],
    year: 2016,
  },
  {
    title: "The Music Room",
    type: "short story",
    handle: "the-music-room",
    originallyPublishedIn: "Playboy (December 2016)",
    collectedIn: "Uncollected",
    notes: ["Included with audio readings of Gwendy's Button Box"],
    year: 2016,
  },
  {
    title: "Gwendy's Button Box",
    type: "novella",
    handle: "gwendy-s-button-box",
    originallyPublishedIn: "Gwendy's Button Box (May 2017)",
    collectedIn: "Uncollected (standalone book)",
    notes: ["written with Richard Chizmar"],
    year: 2017,
  },
  {
    title: "Thin Scenery",
    type: "play",
    handle: "thin-scenery",
    originallyPublishedIn: "Ploughshares (Summer 2017)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2017,
  },
  {
    title: "Laurie",
    type: "short story",
    handle: "laurie",
    originallyPublishedIn: "stephenking.com (May 17, 2018)",
    collectedIn: "Uncollected",
    notes: ["Free download", "[4] included in the Elevation audiobook"],
    year: 2018,
  },
  {
    title: "Elevation",
    type: "novella",
    handle: "elevation",
    originallyPublishedIn: "Elevation (October 2018)",
    collectedIn: "Uncollected (standalone book)",
    notes: [],
    year: 2018,
  },
  {
    title: "The Turbulence Expert",
    type: "short story",
    handle: "the-turbulence-expert",
    originallyPublishedIn: "Flight or Fright (September 4, 2018)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2018,
  },
  {
    title: "Squad D",
    type: "short story",
    handle: "squad-d",
    originallyPublishedIn: "Shivers VIII  (April 18, 2019)",
    collectedIn: "Uncollected",
    notes: ["written in the late 1970s"],
    year: 2019,
  },
  {
    title: "The Fifth Step",
    type: "short story",
    handle: "the-fifth-step",
    originallyPublishedIn: "Harper's Magazine (March 2020)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2020,
  },
  {
    title: "If It Bleeds",
    type: "novella",
    handle: "if-it-bleeds",
    originallyPublishedIn: "If It Bleeds (April 2020)",
    collectedIn: "If It Bleeds (2020)",
    notes: ["First novella in the Holly Gibney Series"],
    year: 2020,
  },
  {
    title: "The Life of Chuck",
    type: "novella",
    handle: "the-life-of-chuck",
    originallyPublishedIn: "If It Bleeds (April 2020)",
    collectedIn: "If It Bleeds (2020)",
    notes: [],
    year: 2020,
  },
  {
    title: "Mr. Harrigan's Phone",
    type: "novella",
    handle: "mr-harrigan-s-phone",
    originallyPublishedIn: "If It Bleeds (April 2020)",
    collectedIn: "If It Bleeds (2020)",
    notes: [],
    year: 2020,
  },
  {
    title: "Rat",
    type: "novella",
    handle: "rat",
    originallyPublishedIn: "If It Bleeds (April 2020)",
    collectedIn: "If It Bleeds (2020)",
    notes: [],
    year: 2020,
  },
  {
    title: "On Slide Inn Road",
    type: "short story",
    handle: "on-slide-inn-road",
    originallyPublishedIn: "Esquire Magazine (October/November 2020)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2020,
  },
  {
    title: "Willie the Weirdo",
    type: "short story",
    handle: "willie-the-weirdo",
    originallyPublishedIn: "McSweeney's 65 (September 2021)",
    collectedIn: "Uncollected",
    notes: [],
    year: 2021,
  },
];
